app/accounts/urls.py
from django.urls import path
from accounts.views import UserSignUpView, LogInView, LogOutView


app_name = 'accounts'

urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout')
]

app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls'), name='quiz'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

app/quiz/urls.py
from django.urls import path
from quiz.views import (
    StudentClassView,
    TeacherCabinetView,
    QuizListView,
    QuizDetailView,
    IndexView,
    CreateQuizView,
    AddQuestionsView,
    AddAnswersView,
    TakenQuizListView,
    TakeQuiz,
    StudentPermissionDenied,
    TeacherPermissionDenied
)


app_name = 'quiz'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('teacher/', TeacherCabinetView.as_view(), name='teacher_cabinet'),
    path('create_quiz', CreateQuizView.as_view(), name='create_quiz'),
    path('<int:pk>/add_questions', AddQuestionsView.as_view(), name='add_question'),
    path('<int:quiz_pk>/<int:question_pk>/add_answers', AddAnswersView.as_view(), name='add_answers'),
    path('student/', StudentClassView.as_view(), name='student_class'),
    path('list/', QuizListView.as_view(), name='quizzes_list'),
    path('quiz/<int:pk>', QuizDetailView.as_view(), name='quiz_detail'),
    path('taken_quiz', TakenQuizListView.as_view(), name='taken_quiz_list'),
    path('student/quiz/<int:pk>', TakeQuiz.as_view(), name='take_quiz'),
    path('teacher/permission-denied', TeacherPermissionDenied.as_view(), name='teacher_permission_denied'),
    path('student/permission-denied', StudentPermissionDenied.as_view(), name='student_permission_denied'),
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from quiz.models import Student, Teacher


class MyUserCreationForm(UserCreationForm):
    is_student = forms.BooleanField(required=False, initial=False)
    is_teacher = forms.BooleanField(required=False, initial=False)
    
    class Meta(UserCreationForm.Meta):
        model = User

    def clean(self):
        cleaned_data = super(MyUserCreationForm, self).clean()
        is_student = cleaned_data.get("is_student")
        is_teacher = cleaned_data.get("is_teacher")
        if is_teacher and is_student:
            self._errors['is_student'] = self.error_class([ 
                'Enter only one of teacher or student']) 
        elif not is_student and not is_teacher:
            self._errors['is_teacher'] = self.error_class([ 
                'You must enter a teacher or a student']) 
        return cleaned_data

    def save(self):
        user = super().save(commit=False)
        is_student = self.cleaned_data.get("is_student")
        is_teacher = self.cleaned_data.get("is_teacher")
        if is_student:  
            user.is_student = True
            user.save()
            student = Student.objects.create(user=user)
        if is_teacher:
            user.is_teacher = True
            user.save()
            teacher = Teacher.objects.create(user=user)
        return user

app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.contrib.auth.forms import AuthenticationForm

from accounts.forms import MyUserCreationForm


class UserSignUpView(TemplateView):

    template_name = 'accounts/signup.html'

    def get(self, request, *args, **kwargs):
        form = MyUserCreationForm()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class LogInView(TemplateView):

    template_name = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                request,
                username=username,
                password=password
                )
            login(request, user)
            if user.is_teacher:
                return redirect('quiz:teacher_cabinet')
            elif user.is_student:
                return redirect('quiz:student_class')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class LogOutView(TemplateView):

    def get(self, request):
        logout(request)
        return redirect('accounts:login')

app/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}ВХОД{% endblock %}

{% block content %}
<div class="section_form">

    <h1 class="title">ВХОД</h1>
    <form class="form" method="POST">
        <div>
            {% csrf_token %}
            
            {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                
                {% for error in field.errors %}
                <p style="color: red">
                    {{ error }}
                </p>
                {% endfor %}
            </p>
            {% endfor %}
            
            <button type="submit">Войти</button>
        </form>
    </div>
    
</div>
        <small>
            Вернуться на <a href="{% url 'quiz:index' %}">Главную страницу</a>
        </small>  
{% endblock %}

app/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<div class="section_form">

    <h1>Регистрация</h1>

    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Регистрация</button>
    </form>
</div>
    
    <small>
        У вас уже есть аккаунт? <a href="{% url "accounts:login" %}">Войти</a>
    </small>
    
    {% endblock %}
    

app/accounts/templates/accounts/signup_student.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h1>Регистрация</h1>
<h2>Роль студента</h2>
Регитрация аккаунта в роли cтудента даёт вам возможность проходить викторины созданные другими
пользователями, если хотите создавать викторины вам необходимо зарегестрироваться в роли учителя
<a href="{% url 'accounts:signup_teacher' %}">
    <button>
        Регистрация в роли учителя
    </button>
</a>

<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Регистрация</button>
</form>

<small>
    У вас уже есть аккаунт? <a href="{% url "accounts:login" %}">Войти</a>
</small>

{% endblock %}