app/accounts/urls.py
from django.urls import path
from accounts.views import UserSignUpView, LogInView, LogOutView


app_name = 'accounts'

urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout')
]

app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls'), name='quiz'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

app/quiz/urls.py
from django.urls import path
from quiz.views import (
    StudentClassView,
    TeacherCabinetView,
    QuizListView,
    QuizDetailView,
    IndexView,
    CreateQuizView,
    AddQuestionsView,
    AddAnswersView,
    TakenQuizListView,
    TakeQuiz,
    StudentPermissionDenied,
    TeacherPermissionDenied
)


app_name = 'quiz'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('teacher/', TeacherCabinetView.as_view(), name='teacher_cabinet'),
    path('create_quiz', CreateQuizView.as_view(), name='create_quiz'),
    path('<int:pk>/add_questions', AddQuestionsView.as_view(), name='add_question'),
    path('<int:quiz_pk>/<int:question_pk>/add_answers', AddAnswersView.as_view(), name='add_answers'),
    path('student/', StudentClassView.as_view(), name='student_class'),
    path('list/', QuizListView.as_view(), name='quizzes_list'),
    path('quiz/<int:pk>', QuizDetailView.as_view(), name='quiz_detail'),
    path('taken_quiz', TakenQuizListView.as_view(), name='taken_quiz_list'),
    path('student/quiz/<int:pk>', TakeQuiz.as_view(), name='take_quiz'),
    path('teacher/permission-denied', TeacherPermissionDenied.as_view(), name='teacher_permission_denied'),
    path('student/permission-denied', StudentPermissionDenied.as_view(), name='student_permission_denied'),
]

app/quiz/models.py
from django.db import models
from accounts.models import User



class Teacher(models.Model):

    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
 
    class Meta:

        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'

        def __str__(self):
            return f'Teacher: {self.user.username}'


class Quiz(models.Model):

    teacher = models.ForeignKey(Teacher, related_name='quizzes', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:

        verbose_name = 'Quiz'       
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return f'Quiz: {self.title}'


class Question(models.Model):

    quiz = models.ForeignKey(Quiz, related_name='questions',on_delete=models.CASCADE)
    text = models.CharField(max_length=255)

    class Meta:

        verbose_name = 'Question'
        verbose_name_plural = 'Questions'

    def __str__(self):
        return f'Question: {self.text}'


class Answer(models.Model):

    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    class Meta:

        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'

    def __str__(self):
        return f'Answer: {self.text}'


class Student(models.Model):

    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')

    class Meta:

        verbose_name = 'Student'
        verbose_name_plural = 'Students'
    
    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return f'Student: {self.user.username}'


class TakenQuiz(models.Model):

    student = models.ForeignKey(Student, related_name='taken_quizzes', on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, related_name='taken_quizzes', on_delete=models.CASCADE)
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:

        verbose_name = 'Taken Quiz'
        verbose_name_plural = 'Taken Quizzes'

    def __str__(self):
        return f'Taken Quiz: {self.quiz}'


class StudentAnswer(models.Model):
    
    user = models.ForeignKey(Student, related_name='quiz_answers', on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:

        verbose_name = 'User Answer'
        verbose_name_plural = 'User Answers'

    def __str__(self):
        return f'{self.answer}'

app/quiz/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from quiz.models import Question, Answer, StudentAnswer
from django.forms.utils import ValidationError

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):

    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')

AnswerFormSet = inlineformset_factory(
        Question,
        Answer,
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

app/quiz/views.py
from django.contrib import messages
from django.db import transaction
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, View
from django.views.generic.detail import DetailView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from quiz.models import Quiz, Question, Answer, StudentAnswer, TakenQuiz
from quiz.forms import QuestionForm, AnswerFormSet, TakeQuizForm
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin


class StudentRequiredMixin(LoginRequiredMixin):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_student:
            return redirect('quiz:student_permission_denied')
        return super(StudentRequiredMixin, self).dispatch(request, *args, **kwargs)


class TeacherRequiredMixin(LoginRequiredMixin):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            return redirect('quiz:teacher_permission_denied')
        return super(TeacherRequiredMixin, self).dispatch(request, *args, **kwargs)


class StudentPermissionDenied(TemplateView):

    template_name = 'quiz/student_permission_denied.html'


class TeacherPermissionDenied(TemplateView):

    template_name = 'quiz/teacher_permission_denied.html'


class IndexView(TemplateView):

    template_name = 'quiz/index.html'


class StudentClassView(StudentPermissionDenied,TemplateView):

    template_name = 'quiz/student_class.html'


class CreateQuizView(TeacherRequiredMixin, CreateView):

    model = Quiz
    fields = ['title', 'description']
    template_name = 'quiz/create_quiz.html'
    
    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.teacher = self.request.user.teacher
        quiz.save()
        return redirect('quiz:add_question', pk=quiz.id)


class AddQuestionsView(TeacherRequiredMixin, CreateView):

    form_class = QuestionForm
    template_name = 'quiz/add_question.html'
    
    quiz = object = None

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, pk=kwargs['pk'], teacher=request.user.teacher)
        return super(AddQuestionsView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        question = form.save(commit=False)
        question.quiz = self.quiz
        question.save()
        return redirect('quiz:add_answers', quiz_pk=self.quiz.id, question_pk=question.id)


class AddAnswersView(TeacherRequiredMixin, CreateView):

    form_class = QuestionForm
    template_name = 'quiz/add_answers.html'
    
    quiz = object = None
    question = object = None

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, pk=kwargs['quiz_pk'], teacher=request.user.teacher)
        self.question = get_object_or_404(Question, pk=kwargs['question_pk'], quiz=self.quiz)
        return super(AddAnswersView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AddAnswersView, self).get_context_data(**kwargs)
        context['formset'] = AnswerFormSet(instance=self.question)
        context['form'] = self.form_class(instance=self.question)
        context['quiz'] = self.quiz
        context['question'] = self.question
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(self.request.POST, instance=self.question)
        formset = AnswerFormSet(self.request.POST, instance=self.question)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        return self.get_context_data

    def form_valid(self, form, formset):
        with transaction.atomic():
            form.save()
            formset.save()
        return redirect('quiz:quiz_detail', pk=self.quiz.id)


class TeacherCabinetView(TeacherRequiredMixin, ListView):

    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'quiz/teacher_cabinet.html'

    def get_queryset(self):
        queryset = self.request.user.teacher.quizzes.annotate(questions_count=Count('questions', distinct=True))
        return queryset


class QuizDetailView(TeacherRequiredMixin, DetailView):

    model = Quiz
    template_name = 'quiz/quiz_detail.html'

    def get_context_data(self, **kwargs):
        context = super(QuizDetailView, self).get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(quiz=context['quiz'])
        return context


class QuizListView(StudentRequiredMixin, ListView):

    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'quiz/quiz_view.html'

    def get_queryset(self):
        student = self.request.user.student
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.all() \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


class TakenQuizListView(StudentRequiredMixin, ListView):

    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'quiz/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz') \
            .order_by('quiz__title')
        return queryset


class TakeQuiz(StudentRequiredMixin, CreateView):

    template_name = 'quiz/take_quiz_form.html'
    form_class = TakeQuizForm

    quiz = object = None

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, pk=kwargs['pk'])
        return super(TakeQuiz, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TakeQuiz, self).get_context_data(**kwargs)
        context['quiz'] = self.quiz
        context['question'] = self.get_question()
        context['progress'] = self.get_progress()

        return context

    def get_form_kwargs(self):
        kwargs = {
            'question': self.get_question(),
        }
        if self.request.method == 'POST':
            kwargs.update({
                'data': self.request.POST,
                'question': self.get_question(),
        })
        return kwargs

    def form_valid(self, form, **kwargs):
        student = self.request.user.student
        student_answer = form.save(commit=False)
        student_answer.user = student
        student_answer.save()
        if student.get_unanswered_questions(self.quiz).exists():
            return redirect('quiz:take_quiz', pk=self.quiz.pk)
        else:
            correct_answers = student.quiz_answers.filter(answer__question__quiz=self.quiz, answer__is_correct=True).count()
            score = round((correct_answers / self.get_total_questions()) * 100.0, 2)
            TakenQuiz.objects.create(student=student, quiz=self.quiz, score=score)
            if score < 50.0:
                messages.warning(self.request, 'Надеемся в дальнейшем вам повезёт больше! За викторину "{quiz}" вы заработали {score} баллов.' \
                    .format(quiz=self.quiz.title, score=score))
            else:
                messages.success(self.request, 'Поздравляем! Вы успешно закончили викторину "{quiz}"! Вы набрали {score} баллов!' \
                    .format(quiz=self.quiz.title, score=score))
            return redirect('quiz:quizzes_list')

    def get_total_questions(self):
        return self.quiz.questions.count()

    def get_progress(self):
        total_questions = self.get_total_questions()
        total_unanswered_questions = self.unanswered_questions().count()
        progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
        return progress

    def unanswered_questions(self):
        return self.request.user.student.get_unanswered_questions(self.quiz)

    def get_question(self):
        question = self.unanswered_questions().first()
        return question

app/quiz/templates/quiz/add_answers.html
Викторина: <a href="{% url 'quiz:quiz_detail' quiz.id %}">{{ quiz.title }}</a> <br>
Вопрос: {{ question.text }}

<h2>{{ question.text }}</h2><br>


  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    {% for error in formset.non_form_errors %}
        {{ error }}
    {% endfor %}
    <table class="table">
        {{ formset.management_form }}

        {% for form in formset.forms %}
            {% if forloop.first %}
                <thead>
                <tr>
                    {% for field in form.visible_fields %}
                        <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% endif %}
            <tr>
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    <input type="submit" value="Сохранить"/> 
</form>

app/quiz/templates/quiz/add_question.html
<form action="" method="POST">
    {%csrf_token%}
    {{form}}
    <button type="submit">
        Сохранить
    </button>
    </form>

app/quiz/templates/quiz/create_quiz.html
<form action="" method="POST">
{%csrf_token%}
{{form}}
<button type="submit">
    Сохранить
</button>
</form>

app/quiz/templates/quiz/index.html
<h1>Добро пожаловать на сайт викторин</h1>

Если вы уже участник нашего сайта просим войти в свой аккаунт <a href="{% url 'accounts:login' %}">ВХОД</a><br>

Если вы здесь впервые, можете зарегистрирроваться <a href="{% url 'accounts:signup' %}">РЕГИСТРАЦИЯ</a>

app/quiz/templates/quiz/quiz_detail.html
<h1>Quiz: {{ quiz.title }}</h1>
<span>Description:</span>
<p>{{ quiz.description }}</p>
<span>Кол-во вопросов : {{ quiz.questions.count }} </span>

{% for question in questions %}
    <div>
        {{question.text}} <a href="{% url 'quiz:add_answers' quiz.pk question.pk %}">Изменить</a>
    </div>
{% endfor %}

<a href="{% url 'quiz:add_question' quiz.id %}">Добавить вопрос</a>

app/quiz/templates/quiz/quiz_view.html
<h1>Список викторин:</h1>
{% if quizzes %}
{% for quiz in quizzes %}
<li>
    {{quiz.title}} <br>
    Кол-во вопросов: {{ quiz.questions_count }} <br>
   <a href="{% url 'quiz:take_quiz' quiz.pk %}">Пройти викторину</a>

</li>
{% endfor %}
{% else %}
<h1>Извиняемся пока нет викторин</h1>
{% endif %}

app/quiz/templates/quiz/studemt_permission_denied.html
<h1>Пользователь не является Студентом</h1>
<p>Для доступа к этой странице требуются особые права</p>

app/quiz/templates/quiz/student_class.html
<h1> Student Class </h1>

<a href="{% url 'quiz:quizzes_list' %}">Список Викторин</a>
<a href="{% url 'quiz:taken_quiz_list' %}">Список пройденных викторин</a>

app/quiz/templates/quiz/take_quiz_form.html
{% extends 'base.html' %}


{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.title }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}

app/quiz/templates/quiz/taken_quiz_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.score }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

app/quiz/templates/quiz/teacher_cabinet.html
<h1>Hello Teacher Cabinet</h1>
{{request.user.username}}

{% for quiz in quizzes %}
    <div>
        {{ quiz.title }}
        {{ quiz.description }}
        {{ quiz.questions_count }}
        <a href="{% url 'quiz:quiz_detail' quiz.pk %}">Подробнее</a>
    </div>
    <br>
{% endfor %}

<a href="{% url 'quiz:create_quiz' %}">Добавить викторину</a>

app/quiz/templates/quiz/teacher_permission_denied.html
<h1>Пользователь не является Учителем</h1>
<p>Для доступа к этой странице требуются особые права</p>

app/quiz/templates/quiz/teacher_quizzes.html
{% for quiz in quizzes %}
    <p>
        {{ quiz }}
        {{ quiz.questions_count }}
        <a href="{% url 'quiz:quiz_detail' quiz.pk %}">Подробнее</a>
    </p>
{% endfor %}

<a href="{% url 'quiz:create_quiz' %}">Добавить викторину</a>